# Arduino Makefile. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno
# BOARD_TAG    = atmega328
ARDUINO_LIBS = AccelStepper LiquidCrystal

include /usr/share/arduino/Arduino.mk

