# Arduino Makefile. Refer to https://github.com/sudar/Arduino-Makefile

# For a breadboard chip using internal clock:
ARDUINO_DIR = /usr/local/share/arduino

ALTERNATE_CORE = breadboard
BOARD_TAG    = atmega328bb

# BOARD_SUB isn't actually needed for atmega328.
# BOARD_SUB    = atmega328

ISP_PROG     = usbtiny
# To upload programs using the usbtinyisp: make ispload

include /usr/share/arduino/Arduino.mk

