# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_DIR = /usr/local/share/arduino

ARCHITECTURE  = avr
BOARD_TAG    = uno

USER_LIB_PATH += /home/akkana/sketchbook/libraries

ARDUINO_LIBS += FastLED

include /usr/share/arduino/Arduino.mk
