# Arduino Makefile. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_DIR = /usr/local/share/arduino

ALTERNATE_CORE = breadboard

BOARD_TAG    = atmega328bb
BOARD_SUB    = atmega328

ARDUINO_LIBS = FastLED

ISP_PROG     = usbtiny
# To upload programs using the usbtinyisp: make ispload

include /usr/share/arduino/Arduino.mk

