
# Useful discussion of various ways of specifying alternate cores:
# https://github.com/sudar/Arduino-Makefile/issues/121

ARDUINO_DIR = /usr/local/share/arduino

ALTERNATE_CORE = tiny
BOARD_TAG = attiny85at8

F_CPU = 1000000L
ISP_PROG = usbtiny

include /usr/local/share/Arduino-Makefile/Arduino.mk


