# Arduino Makefile. Refer to https://github.com/sudar/Arduino-Makefile

# make show_boards
# to see a list

BOARD_TAG    = uno

# BOARD_TAG    = diecimila
# BOARD_TAG    = nano328
# BOARD_SUB    = atmega328

# Megas need a BOARD_SUB, which you can get like
# make ARDUINO_QUIET=1 show_submenu | grep 2560
# BOARD_TAG    = mega
# BOARD_SUB = atmega2560

# For a breadboard arduino with internal clock, uncomment these two lines:
# ALTERNATE_CORE = breadboard
# BOARD_TAG      = atmega328bb

# How to use the usbtinyisp to upload programs:
# ISP_PROG     = usbtiny
# then use: make ispload

# include /usr/share/arduino/Arduino.mk
include /usr/local/share/Arduino-Makefile/Arduino.mk

