# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno

# How to use the usbtinyisp to upload programs:
# BOARD_TAG    = nano328
# ISP_PROG     = usbtiny
# then use: make ispload

include /usr/share/arduino/Arduino.mk

