# Arduino Makefile. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = uno

ARDUINO_LIBS = Encoder

# include /usr/share/arduino/Arduino.mk
include /usr/local/share/Arduino-Makefile/Arduino.mk

