# Arduino Makefile. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_LIBS = Wire

ALTERNATE_CORE    = arduino-tiny
ISP_PROG          = usbtiny
BOARD_TAG         = attiny85at8

include /usr/share/arduino/Arduino.mk

