# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# BOARD_TAG    = uno

# For a breadboard chip using internal clock:
ALTERNATE_CORE = breadboard
BOARD_TAG    = atmega328bb

ISP_PROG     = usbtiny
# To upload programs using the usbtinyisp: make ispload

ARDUINO_LIBS = LiquidCrystal

include /usr/share/arduino/Arduino.mk

