# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# If using /usr/share/arduino, the version installed by Debian,
# don't specify ARCHITECTURE. I guess avr is the only archiecture
# included by Debian and there's no separate avr path.
# But it also lacks important libraries like HardwareSerial.
# ARDUINO_DIR = /usr/share/arduino

ARDUINO_DIR = /usr/local/share/arduino

ARCHITECTURE  = avr
BOARD_TAG    = uno

include /usr/share/arduino/Arduino.mk

