# Arduino Makefile. Refer to https://github.com/sudar/Arduino-Makefile

# ALTERNATE_CORE = breadboard

# BOARD_TAG      = atmega328bb

BOARD_TAG    = uno
# BOARD_TAG    = diecimila
# BOARD_TAG    = nano328
# BOARD_SUB    = atmega328

# How to use the usbtinyisp to upload programs:
ISP_PROG     = usbtiny
# then use: make ispload

# include /usr/share/arduino/Arduino.mk
include /usr/local/share/Arduino-Makefile/Arduino.mk

